
// 1)
class CSSInjectPlugin {
    apply(compiler) {
      compiler.hooks.emit.tapAsync('CSSInjectPlugin', (compilation, callback) => {
        // Check if the CSS file has been generated
        // const cssFile = compilation.assets['styles.css'];
        const cssContent = compilation.__cssAccumulator
        if (cssContent) {
  
          // Modify the HTML file to inject the CSS into a <style> tag
          const htmlFile = compilation.assets['index.html'];
          if (htmlFile) {
            const htmlContent = htmlFile.source();
            const modifiedHTML = htmlContent.replace(
              '</head>',
              `<style>${cssContent}</style></head>`
            );
  
            // Update the HTML file in the compilation
            compilation.assets['index.html'] = {
              source: () => modifiedHTML,
              size: () => modifiedHTML.length,
            };
          }
        }
        callback();
      });
    }
  }
  
  module.exports = CSSInjectPlugin;
  




// 2)
// class CSSInjectPlugin {
//     apply(compiler) {
//       compiler.hooks.thisCompilation.tap('CSSInjectPlugin', (compilation) => {
//         compilation.hooks.processAssets.tap(
//           {
//             name: 'CSSInjectPlugin',
//             stage: compilation.PROCESS_ASSETS_STAGE_ADDITIONAL,
//           },
//           (assets) => {
//             // Assuming you are emitting `styles.css` file earlier
//             const cssFileName = 'styles.css';
//             const cssContent = assets[cssFileName] ? assets[cssFileName].source() : '';
  
//             // Now inject CSS into HTML or wherever required
//             const htmlFileName = 'index.html'; // Assuming index.html exists in assets
//             if (assets[htmlFileName]) {
//               const originalHtml = assets[htmlFileName].source();
//               const updatedHtml = originalHtml.replace(
//                 '</head>',
//                 `<style>${cssContent}</style></head>`
//               );
  
//               // Replace the old HTML with the new one containing injected CSS
//               assets[htmlFileName] = {
//                 source: () => updatedHtml,
//                 size: () => updatedHtml.length,
//               };
//             }
//           }
//         );
//       });
//     }
//   }
  
//   module.exports = CSSInjectPlugin;
  


// 3)
// class CssInjectPlugin {
//     apply(compiler) {
//       // Hook into the compilation process at the right stage
//       compiler.hooks.compilation.tap('CssInjectPlugin', (compilation) => {
//         compilation.hooks.processAssets.tap(
//           {
//             name: 'CssInjectPlugin',
//             stage: compilation.PROCESS_ASSETS_STAGE_ADDITIONS,
//           },
//           (assets) => {
//             // Retrieve the CSS file that was created by the loader
//             const cssFileName = Object.keys(assets).find((asset) => asset.endsWith('.css'));
  
//             // If there's a CSS file, inject it into the HTML file
//             // console.log("CSS FILE NAME : ", cssFileName)
//             if (cssFileName) {
//               const cssContent = assets[cssFileName].source();
//             //   console.log("CSS CONTENT : ", cssContent)
//               const htmlFileName = Object.keys(assets).find((asset) => asset.endsWith('.html'));
//               console.log("HTML FILE NAME: ", htmlFileName)
  
//               if (htmlFileName) {
//                 const htmlSource = assets[htmlFileName].source();
//                 const updatedHtml = htmlSource.replace(
//                   '</head>',
//                   `<style>${cssContent}</style></head>`
//                 );
  
//                 // Update the HTML file with the injected CSS
//                 assets[htmlFileName] = {
//                   source: () => updatedHtml,
//                   size: () => updatedHtml.length,
//                 };
//               }
//             }
//           }
//         );
//       });
//     }
//   }
  
//   module.exports = CssInjectPlugin;
  







// 4)
// class CssInjectPlugin {
//     apply(compiler) {
//       compiler.hooks.afterEmit.tapAsync('CssInjectPlugin', (compilation, callback) => {
//         // Find the CSS file created by the CSS loader
//         const cssFileName = Object.keys(compilation.assets).find((asset) => asset.endsWith('.css'));
  
//         // If CSS file exists
//         if (cssFileName) {
//           // Find the HTML file generated by HtmlWebpackPlugin
//           const htmlFileName = Object.keys(compilation.assets).find((asset) => asset.endsWith('.html'));
  
//           if (htmlFileName) {
//             // Read the content of the HTML file
//             const htmlSource = compilation.assets[htmlFileName].source();
  
//             // Read the CSS content
//             const cssContent = compilation.assets[cssFileName].source();
  
//             // Inject the CSS into the <head> of the HTML
//             const updatedHtml = htmlSource.replace(
//               '</head>',
//               `<style>${cssContent}</style></head>`
//             );
  
//             // Overwrite the HTML file with the new content
//             compilation.assets[htmlFileName] = {
//               source: () => updatedHtml,
//               size: () => updatedHtml.length,
//             };
//           }
//         }
        
//         callback();
//       });
//     }
//   }
  
//   module.exports = CssInjectPlugin;
  


  // 5)
//   class CssInjectPlugin {
//     apply(compiler) {
//         // Hook into the compilation process at the right stage
//         compiler.hooks.compilation.tap('CssInjectPlugin', (compilation) => {
//         compilation.hooks.processAssets.tap(
//             {
//             name: 'CssInjectPlugin',
//             stage: compilation.PROCESS_ASSETS_STAGE_ADDITIONS,
//             },
//             (assets) => {
//             // Retrieve the CSS file that was created by the loader
//             const cssFileName = Object.keys(assets).find((asset) => asset.endsWith('.css'));
    
//             // If there's a CSS file, inject it into the HTML file
//             // console.log("CSS FILE NAME : ", cssFileName)
//             if (cssFileName) {
//                 const cssContent = assets[cssFileName].source();
//             //   console.log("CSS CONTENT : ", cssContent)
//                 const htmlFileName = Object.keys(assets).find((asset) => asset.endsWith('.html'));
//                 console.log("HTML FILE NAME: ", htmlFileName)
    
//                 if (htmlFileName) {
//                 const htmlSource = assets[htmlFileName].source();
//                 const updatedHtml = htmlSource.replace(
//                     '</head>',
//                     `<style>${cssContent}</style></head>`
//                 );
    
//                 // Update the HTML file with the injected CSS
//                 assets[htmlFileName] = {
//                     source: () => updatedHtml,
//                     size: () => updatedHtml.length,
//                 };
//                 }
//             }
//             }
//         );
//         });
//     }
//     }
    
//     module.exports = CssInjectPlugin;


// 6)
// module.exports = function(source) {
//   const loaderContext = this;

//   // Ensure that we reset the accumulator at the start of each build
//   loaderContext._compiler.hooks.beforeCompile.tap('CssMergePlugin', () => {
//     cssAccumulator.length = 0; // Clear the array
//   });

//   // Accumulate the CSS content
//   cssAccumulator.push(source);

//   // Emit the final concatenated CSS in the emit phase
//   loaderContext._compiler.hooks.emit.tapAsync('CssMergePlugin', (compilation, callback) => {
//     const finalCss = cssAccumulator.join('\n');
//     compilation.emitAsset('style.css', {
//       source: () => finalCss,
//       size: () => finalCss.length
//     });
//     callback();
//   });

//   return source;
// };


// 7)
// class CssInjectPlugin {
//     apply(compiler) {
//         // Hook into the compilation process at the right stage
//         compiler.hooks.thisCompilation.tap('CssInjectPlugin', (compilation) => {
//         compilation.hooks.processAssets.tap(
//             {
//             name: 'CssInjectPlugin',
//             stage: compilation.PROCESS_ASSETS_STAGE_SUMMARIZE,
//             },
//             (assets) => {
//             // Retrieve the CSS file that was created by the loader
//             // const cssFileName = Object.keys(assets).find((asset) => asset.endsWith('.css'));
//             const cssFileName = true
//             console.log(assets)
//             console.log(compilation.__cssAccumulator)
//             // console.log(compilation)
    
//             // If there's a CSS file, inject it into the HTML file
//             // console.log("CSS FILE NAME : ", cssFileName)
//             if (cssFileName) {
//                 // const cssContent = assets[cssFileName].source();
//                 const cssContent = "div{color:'red'}"
//             //   console.log("CSS CONTENT : ", cssContent)
//                 const htmlFileName = Object.keys(assets).find((asset) => asset.endsWith('.html'));
//                 console.log("HTML FILE NAME: ", htmlFileName)
    
//                 if (htmlFileName) {
//                 const htmlSource = assets[htmlFileName].source();
//                 console.log("html source : ", htmlSource)
//                 const updatedHtml = htmlSource.replace(
//                     '</head>',
//                     `<style>${cssContent}</style></head>`
//                 );
    
//                 // Update the HTML file with the injected CSS
//                 assets[htmlFileName] = {
//                     source: () => updatedHtml,
//                     size: () => updatedHtml.length,
//                 };
//                 }
//             }
//             }
//         );
//         });
//     }
//     }
    
//     module.exports = CssInjectPlugin;
  